version: '3.9'
services:
  backend:
    build:
      context: ./backend
    command: sh -c "python ./medicine_alert/manage.py runserver 0.0.0.0:8000 || bash"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    tty: true
  frontend:
    build:
      context: ./frontend
    command: sh -c "npm start || bash"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/medicine-alert/:/app
    depends_on:
      - backend
    tty: true
  db:
    image: postgres:13.2
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: